server:
  port: 8080

#spring:
#  aop:
#    proxy-target-class: true

chat-bot:
  classId:  # 课程ID
  cookie:   # 雨课堂cookie
  proxyHost:  # 代理服务器地址
  proxyPort:  # 代理服务器端口
  openAIToken:  # OpneAI API Token
